### ISSUE TITLE
Convert Libraries to package_name.core.dll

### ISSUE THREAD

**Issue by tilkinsc** [xiedacon/lua-utility#1]
Hey! Creator of [LuaConsole](https://github.com/tilkinsc/LuaConsole)!

Nice collection.

Do you think these libraries could benefit from being written in C/C++?

**Comment by xiedacon** [comment]
Hi, tilkinsc. Thanks for your issue.

If rewrite these libraries by C/C++: 

1. ``utility.array`` and ``utility.object`` may have some problem, because convert C/C++ object to Lua object will trigger a lot of GC in high concurrency.
2. ``utility.string``'s performance will be improved.

And in my opinion, written these libraries in Lua make it easy to read and understand.
